home work 41
NataliiaFed/RobotDreams pull request #27
Opened 2023-05-08 00:09 UTC by NataliiaFed

Home work 41

2023-05-08 10:52 UTC, klymenok requested changes

2023-05-08 10:52 UTC, klymenok commented on django/book/migrations/__pycache__/0001_initial.cpython-311.pyc
__pycache__ не потрібно пушити на репозиторій

2023-05-08 10:52 UTC, klymenok commented on django/book/models.py
> -    def __str__(self):
Не потрібно було видаляти __str__ для моделей. Відображення в адмін панелі має залишатися таким яким і було

2023-05-08 10:52 UTC, klymenok commented on django/book/models.py
> -    def __str__(self):
Це стосується і інших моделей

2023-05-08 11:17 UTC, NataliiaFed commented on django/book/migrations/__pycache__/0001_initial.cpython-311.pyc
Не розумію, чому pycache  пушиться. Я додала pycache до gitignore, але вони все одно пушаться

2023-05-11 16:37 UTC, klymenok approved these changes

2023-05-12 08:46 UTC, merged