add home work 11
NataliiaFed/RobotDreams pull request #7
Opened 2023-01-16 11:08 UTC by NataliiaFed

add home work #11

2023-01-16 23:36 UTC, klymenok requested changes

2023-01-16 23:36 UTC, klymenok commented on homework_10,11.py
> +    def deco_func(*args):
Use **kwargs here as well

2023-01-16 23:36 UTC, klymenok commented on homework_10,11.py
> +        func(*args)
Use `return` statement here to be able to decorate functions that return some value. And add **kwargs here

2023-01-18 21:38 UTC, klymenok requested changes

2023-01-18 21:38 UTC, klymenok commented on homework_10,11.py
> +# # ===============================================================================================
Why is all this code commented off?

2023-01-18 21:38 UTC, klymenok commented on homework_10,11.py
> +        return round(result, 0)
This code will raise an exception if you decorate a function that returns a string, for example.
Leave it just as `return result`

2023-01-18 21:51 UTC, NataliiaFed commented on homework_10,11.py
> +# # ===============================================================================================
oops, forgot to uncomment

2023-01-21 16:58 UTC, klymenok approved these changes
Looks good!

2023-01-22 22:12 UTC, merged